### ISSUE TITLE
Add linting (JS, HTML, etc.)

### ISSUE THREAD

**Issue by rgladwell** [grislyeye/vellum-stat-block#1]
Add linting to the build process for:
 - [x] Polymer
 - [ ] JavaScript
 - [ ] CSS
 - [ ] HTML

**Comment by rgladwell** [comment]
Maybe use [html-linter](https://www.npmjs.com/package/html-linter)?

**Comment by rg-wood** [comment]
This issue was moved to grislyeye/temp#1
